### PR TITLE
Minecraft Legends plugin for Blockbench

### PR DESCRIPTION
**Pull request by williamharmon**
This is the .js file that blockbench targets when installing the plugin. This doesn't include anything from the src directory. That's fine, right?

### CODE REVIEW

**Comment by jsyarrow** [comment]
For this repo we want the ```src``` folder too.

**Comment by williamharmon** [comment]
> 

just  `legends-blockbench-plugin\Source\src`, or do we want the other contents of `Source`:
```
Directory of C:\legends-blockbench-plugin\Source

06/21/2023  10:35 AM            13,873 package-lock.json
06/21/2023  10:35 AM               428 package.json
07/07/2023  08:16 AM    <DIR>          src
06/21/2023  10:35 AM               164 tsconfig.json
07/07/2023  08:16 AM    <DIR>          types
```

**Comment by jsyarrow** [comment]
Looks to me like we want all of that stuff.

**Review by jsyarrow — APPROVED** [review]
Good to go on this one!

**Pull request merged**
